#!/bin/sh
########################################################################
# Watchdog over Plex server, keeps them alive if possible.
########################################################################

PRGNAM=plexwatch
LOGFILE=/var/log/$PRGNAM.log

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$LOGFILE 2>&1

plexApps="plexmediaserver nzbget radarr sonarr lidarr ombi"
plexPorts="32400/web 6799 7878 8989 8686 5000"

for i in ${!plexApps[@]}; do
	APP=${plexApps[$i]}
	PORT=${plexPorts[$i]}
	if [ $(/etc/rc.d/rc."$i" status | grep -q 'stopped') ]; then
		echo "$(date) : $i is stopped. Attempting to start."
		/etc/rc.d/rc.$i start
		if $? -ne 0; then
			echo "$(date) : Error starting $i."
		fi
	fi
done

echo "$(date) : $PRGNAM complete."

exit 0

