#!/bin/bash

for i in $(find . -maxdepth 2 -mindepth 1 -type d); do
	pushd $i >/dev/null
	if [ -r *.SlackBuild ]; then
        cd ../../
        bash ../latest-version/"$i"-lv.sh
        cd -
	fi
	popd >/dev/null
done
