#!/bin/sh

# Slackware build script for unifi

# Copyright 2021 Justin Teague <arcadellama@posteo.net>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=unifi-controller
VERSION=${VERSION:-6.1.71}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

UNIFI_USER=${UNIFI_USER:-unifi}
UNIFI_GROUP=${UNIFI_GROUP:-unifi}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

# Bail if user or group isn't valid on your system
if ! getent passwd $UNIFI_USER 1>/dev/null 2>/dev/null; then
  cat << EOF

  You must have a ombi user to run this script

  # groupadd $UNIFI_GROUP
  # useradd -r -d /var/lib/$PRGNAM -g $UNIFI_GROUP $UNIFI_USER

EOF

  exit 1
elif ! getent group $UNIFI_GROUP 1>/dev/null 2>/dev/null; then
  cat << EOF

  You must have a ombi group to run this script
  # groupadd $UNIFI_GROUP

EOF
  exit 1
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf UniFi
unzip $CWD/UniFi.unix.zip
cd UniFi
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p $PKG/usr/lib/$PRGNAM/
cp -r {bin,dl,lib,webapps} $PKG/usr/lib/$PRGNAM
rm -rf $PKG/usr/lib/$PRGNAM/lib/native/{Mac,Windows}

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/etc/rc.d
sed -e "s/@UNIFI_USER@/${UNIFI_USER}/g" \
	-e "s/@UNIFI_GROUP@/${UNIFI_GROUP}/g" \
	$CWD/rc.$PRGNAM > $PKG/etc/rc.d/rc.$PRGNAM.new
chmod 755 $PKG/etc/rc.d/rc.$PRGNAM.new

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat readme.txt > $PKG/usr/doc/$PRGNAM-$VERSION/readme.txt
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README.SLACKBUILD
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
