#!/bin/sh
########################################################################
# Watchdog over Plex server, keeps them alive if possible.
########################################################################

PRGNAM=plexwatch
LOGFILE=/var/log/$PRGNAM.log

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$LOGFILE 2>&1

plexApps="plexmediaserver nzbget radarr sonarr lidarr ombi"

for i in $PLEXAPPS; do
	if [ $(/etc/rc.d/rc."$i" status | grep -q 'stopped') ]; then
		echo "$(date) : $i is stopped. Attempting to start."
		/etc/rc.d/rc.$i start
	fi
done

exit 0
